kind: ConfigMap
apiVersion: v1
metadata:
  name: client-properties
  immutable: false
data:
  client.properties: |-
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=SCRAM-SHA-256
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
        username="user1" \
        password="$(oc get secret kafka-user-passwords --namespace loic-mulder-dev -o jsonpath='{.data.client-passwords}' | base64 -d | cut -d , -f 1)";
