kind: Service
apiVersion: v1
metadata:
  name: debezium
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: debezium