kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: mysql